function [x,Body] = Runge_Kutta_4_ControlledDynamicModel(...
	x,ModelParameter,Action,Ts)
%%
k_1 = Controlled_Multi_Body_Dynamics_func(...
	x,ModelParameter,Action);
k_2 = Controlled_Multi_Body_Dynamics_func(...
	x+0.5*Ts*k_1,ModelParameter,Action);
k_3 = Controlled_Multi_Body_Dynamics_func(...
	x+0.5*Ts*k_2,ModelParameter,Action);
k_4 = Controlled_Multi_Body_Dynamics_func(...
	x+k_3*Ts,ModelParameter,Action);
%%
x = x + (1/6)*(k_1+2*k_2+2*k_3+k_4)*Ts;
[~,Body] = Controlled_Multi_Body_Dynamics_func(...
	x,ModelParameter,Action);

end