function [MassJacobian,ForceJacobian_q,ForceJacobian_dq,ForceJacobian_u] ...
	= get_MassForce_JacobianMatrix_Multi_Body_Dynamic(...
	x,MassForce_JacobianFunc,MassJacobianBase)
%%
Jacobian_x = x;
Jacobian_x(Jacobian_x == 0) = eps;
%%
if isempty(MassJacobianBase)
	MassJacobianBase = ones(numel(Jacobian_x)/2,1);
end
MassForce_StateVariable_Jacobian = ...
	MassForce_JacobianFunc(...
	'q',Jacobian_x(1:numel(Jacobian_x)/2), ...
	'dq',Jacobian_x(numel(Jacobian_x)/2+1:end), ...
	'b',MassJacobianBase);
%%
MassJacobian = ...
	full(MassForce_StateVariable_Jacobian.MassJacobian);
ForceJacobian_q = ...
	full(MassForce_StateVariable_Jacobian.ForceJacobian_q);
ForceJacobian_dq = ...
	full(MassForce_StateVariable_Jacobian.ForceJacobian_dq);
ForceJacobian_u = ...
	full(MassForce_StateVariable_Jacobian.ForceJacobian_u);
end