function ActionFunction = get_ActionFunction(ActionFunctionTag)
switch ActionFunctionTag
	case 'None'
		ActionFunction = ...
			@(t,x,tspan,ModelParameter)get_Action_None(...
			t,x,tspan,ModelParameter);
% TestType = 'Rotation_x';
% TestType = 'Translation_x';
%
% SolverParameter.ActionFunction = ...
% 	@(t,x,tspan,ModelParameter)get_Action_Truss_Dynamics_Test(...
% 	t,x,tspan,ModelParameter,TestType);



% SolverParameter.ActionFunction = ...
% 	@(t,x,tspan,ModelParameter)get_Action_FoldingBoom(...
% 	t,x,tspan,ModelParameter);

% ActionFunction = ...
% 	@(t,x,tspan,ModelParameter)get_Action_LoadControl(...
% 	t,x,tspan,ModelParameter);
end

end