function ElectronicThrottleValve_Parameter = create_ElectronicThrottleValve(...
	HydraulicElementParameterTableRaw,HydraulicElementNr,ParameterStartPosition, ...
	HydraulicCoordinateQuantity,CoordinateQuantity)
%%
ElectronicThrottleValve_Parameter.Type = HydraulicElementParameterTableRaw{...
	ParameterStartPosition+1,HydraulicElementNr+3};
ElectronicThrottleValve_Parameter.A = HydraulicElementParameterTableRaw{...
	ParameterStartPosition+2,HydraulicElementNr+3};
ElectronicThrottleValve_Parameter.cq = HydraulicElementParameterTableRaw{...
	ParameterStartPosition+3,HydraulicElementNr+3};
ElectronicThrottleValve_Parameter.Control = HydraulicElementParameterTableRaw{...
	ParameterStartPosition+4,HydraulicElementNr+3};
ElectronicThrottleValve_Parameter.pmin = HydraulicElementParameterTableRaw{...
	ParameterStartPosition+5,HydraulicElementNr+3};
ElectronicThrottleValve_Parameter.pmax = HydraulicElementParameterTableRaw{...
	ParameterStartPosition+6,HydraulicElementNr+3};

ElectronicThrottleValve_Parameter.GlobalCoordinate = ...
	HydraulicCoordinateQuantity + [1:CoordinateQuantity];
%%
ElectronicThrottleValve_Parameter.Coordinate.p{1} = ...
	ElectronicThrottleValve_Parameter.GlobalCoordinate(1);
ElectronicThrottleValve_Parameter.Coordinate.p{2} = ...
	ElectronicThrottleValve_Parameter.GlobalCoordinate(2);
ElectronicThrottleValve_Parameter.Coordinate.Q{1} = ...
	ElectronicThrottleValve_Parameter.GlobalCoordinate(3);
ElectronicThrottleValve_Parameter.Coordinate.Q{2} = ...
	ElectronicThrottleValve_Parameter.GlobalCoordinate(4);
%
ElectronicThrottleValve_Parameter.SymbolicCoordinate.p{1} = ...
	sym(['p_',num2str(HydraulicElementNr),'_',num2str(1)]);
ElectronicThrottleValve_Parameter.SymbolicCoordinate.p{2} = ...
	sym(['p_',num2str(HydraulicElementNr),'_',num2str(2)]);
ElectronicThrottleValve_Parameter.SymbolicCoordinate.Q{1} = ...
	sym(['Q_',num2str(HydraulicElementNr),'_',num2str(1)]);
ElectronicThrottleValve_Parameter.SymbolicCoordinate.Q{2} = ...
	sym(['Q_',num2str(HydraulicElementNr),'_',num2str(2)]);
%%
for ControlNr = 1:numel(ElectronicThrottleValve_Parameter.Control)
    ElectronicThrottleValve_Parameter.SymbolicControl = ...
        sym(['u_',num2str(ElectronicThrottleValve_Parameter.Control)]);
end
end