function IdealConstantPressurePumpParameter = create_IdealConstantPressurePump(...
	HydraulicElementParameterTableRaw,HydraulicElementNr,ParameterStartPosition, ...
	HydraulicCoordinateQuantity,CoordinateQuantity)
%%
IdealConstantPressurePumpParameter.p = HydraulicElementParameterTableRaw{...
	ParameterStartPosition+1,HydraulicElementNr+3};
IdealConstantPressurePumpParameter.Qmax = HydraulicElementParameterTableRaw{...
	ParameterStartPosition+2,HydraulicElementNr+3};
IdealConstantPressurePumpParameter.GlobalCoordinate = ...
	HydraulicCoordinateQuantity + [1:CoordinateQuantity];
%%
if IdealConstantPressurePumpParameter.Qmax == -1
	IdealConstantPressurePumpParameter.Qmax = Inf;
end
%%
IdealConstantPressurePumpParameter.Coordinate.p{1} = ...
	IdealConstantPressurePumpParameter.GlobalCoordinate(1);
IdealConstantPressurePumpParameter.Coordinate.Q{1} = ...
	IdealConstantPressurePumpParameter.GlobalCoordinate(2);
%
IdealConstantPressurePumpParameter.SymbolicCoordinate.p{1} = ...
	sym(['p_',num2str(HydraulicElementNr),'_',num2str(1)]);
IdealConstantPressurePumpParameter.SymbolicCoordinate.Q{1} = ...
	sym(['Q_',num2str(HydraulicElementNr),'_',num2str(1)]);
end