function DoubleActingHydraulicCylinder_Parameter = create_DoubleActingHydraulicCylinder(...
	HydraulicElementParameterTableRaw,HydraulicElementNr,ParameterStartPosition, ...
	HydraulicCoordinateQuantity,CoordinateQuantity)
%%
DoubleActingHydraulicCylinder_Parameter.A = HydraulicElementParameterTableRaw{...
	ParameterStartPosition+1,HydraulicElementNr+3};
DoubleActingHydraulicCylinder_Parameter.L = HydraulicElementParameterTableRaw{...
	ParameterStartPosition+2,HydraulicElementNr+3};
DoubleActingHydraulicCylinder_Parameter.alpha = HydraulicElementParameterTableRaw{...
	ParameterStartPosition+3,HydraulicElementNr+3};
DoubleActingHydraulicCylinder_Parameter.Lmin = HydraulicElementParameterTableRaw{...
	ParameterStartPosition+4,HydraulicElementNr+3};
DoubleActingHydraulicCylinder_Parameter.Lmax = HydraulicElementParameterTableRaw{...
	ParameterStartPosition+5,HydraulicElementNr+3};
DoubleActingHydraulicCylinder_Parameter.StateVariable = str2num(...
	HydraulicElementParameterTableRaw{...
	ParameterStartPosition+6,HydraulicElementNr+3});

DoubleActingHydraulicCylinder_Parameter.GlobalCoordinate = ...
	HydraulicCoordinateQuantity + [1:CoordinateQuantity];
%%
DoubleActingHydraulicCylinder_Parameter.Coordinate.p{1} = ...
	DoubleActingHydraulicCylinder_Parameter.GlobalCoordinate(1);
DoubleActingHydraulicCylinder_Parameter.Coordinate.p{2} = ...
	DoubleActingHydraulicCylinder_Parameter.GlobalCoordinate(2);
DoubleActingHydraulicCylinder_Parameter.Coordinate.Q{1} = ...
	DoubleActingHydraulicCylinder_Parameter.GlobalCoordinate(3);
DoubleActingHydraulicCylinder_Parameter.Coordinate.Q{2} = ...
	DoubleActingHydraulicCylinder_Parameter.GlobalCoordinate(4);
%
DoubleActingHydraulicCylinder_Parameter.SymbolicCoordinate.p{1} = ...
	sym(['p_',num2str(HydraulicElementNr),'_',num2str(1)]);
DoubleActingHydraulicCylinder_Parameter.SymbolicCoordinate.p{2} = ...
	sym(['p_',num2str(HydraulicElementNr),'_',num2str(2)]);
DoubleActingHydraulicCylinder_Parameter.SymbolicCoordinate.Q{1} = ...
	sym(['Q_',num2str(HydraulicElementNr),'_',num2str(1)]);
DoubleActingHydraulicCylinder_Parameter.SymbolicCoordinate.Q{2} = ...
	sym(['Q_',num2str(HydraulicElementNr),'_',num2str(2)]);
%%
for StateVariableNr = 1:numel(DoubleActingHydraulicCylinder_Parameter.StateVariable)
    DoubleActingHydraulicCylinder_Parameter.SymbolicStateVariable{StateVariableNr} = ...
        sym(['x_',num2str(DoubleActingHydraulicCylinder_Parameter.StateVariable(StateVariableNr))]);
end
end