function SubBeamParameter = set_Truss_SubBeam_Parameter(SubBeamType,...
	TrussOrder,TrussLength,MainBeamParameter,CrossSectionParameter,PlaneParameter, ...
	BodyParameterTableRaw,BodyNr)
%%
switch SubBeamType
	case 'Type1'
		SubBeamParameter = set_Truss_SubBeam_Parameter_Type1(...
			TrussOrder,TrussLength,...
			MainBeamParameter,CrossSectionParameter,PlaneParameter, ...
			BodyParameterTableRaw,BodyNr);
	case 'TP Type1'% Triangular Prism Type1
		SubBeamParameter = set_Truss_SubBeam_Parameter_TP_Type1(...
			TrussOrder,TrussLength,...
			MainBeamParameter,CrossSectionParameter,PlaneParameter, ...
			BodyParameterTableRaw,BodyNr);
    case 'TP Anti Type1'
        SubBeamParameter = set_Truss_SubBeam_Parameter_TP_Anti_Type1(...
			TrussOrder,TrussLength,...
			MainBeamParameter,CrossSectionParameter,PlaneParameter, ...
			BodyParameterTableRaw,BodyNr);
	case 'Pyramid Type1'
		SubBeamParameter = set_Truss_SubBeam_Parameter_Pyramid_Type1(...
			TrussOrder,TrussLength,...
			MainBeamParameter,CrossSectionParameter,PlaneParameter, ...
			BodyParameterTableRaw,BodyNr);
	case 'None'
		SubBeamParameter = set_Truss_SubBeam_Parameter_None;
	otherwise
		SubBeamParameter = set_Truss_SubBeam_Parameter_None;
end

end

