%% Hydraulic_System_Test
clear;clc;close all;
%%
x = zeros(10,1);
x(7:10) = [3e7;1.5e6;3e7;1.5e6]/1e5;
u = 1*[0;1;1];
%%
ExcelFilePath = 'Parameter File\Hydraulic System Test\Hydraulic System Test - 1.xlsx';

[HydraulicOilParameter,HydraulicElementParameter,HydraulicCoordinateQuantity] = ...
	create_HydraulicElement(ExcelFilePath);

HydraulicConnectionParameter = create_HydraulicConnection(ExcelFilePath);

HydraulicSymbolicStateSolution = create_HydraulicCalculationEquation(...
	HydraulicOilParameter,HydraulicElementParameter, ...
	HydraulicConnectionParameter);

% [HydraulicNumericalEquation] = ...
% 	create_HydraulicCalculationEquation_Numerical(HydraulicState,x,u, ...
% 	HydraulicOilParameter,HydraulicElementParameter, ...
% 	HydraulicConnectionParameter);
%%
HydraulicParameter.HydraulicElementParameter = HydraulicElementParameter;
HydraulicParameter.HydraulicOilParameter = HydraulicOilParameter;
HydraulicParameter.HydraulicEquation = HydraulicSymbolicStateSolution;

HydraulicParameter.HydraulicCoordinateQuantity = HydraulicCoordinateQuantity;
HydraulicParameter.HydraulicNumericalEquationHandle = ...
	@(HydraulicState)create_HydraulicCalculationEquation_Numerical(HydraulicState,x,u, ...
	HydraulicOilParameter,HydraulicElementParameter, ...
	HydraulicConnectionParameter);
%%
fprintf('symbolic calculation time:\n');
tic;
HydraulicElementState = solve_HydraulicCalculationEquatition(...
	x,u,HydraulicSymbolicStateSolution);
toc;

InitialHydraulicState = zeros(HydraulicCoordinateQuantity,1);
HydraulicState = InitialHydraulicState;

opt = optimoptions('fsolve', ...
	'Algorithm','trust-region-dogleg', ...
	'StepTolerance',1e-15, ...
	'FunctionTolerance',1e-15, ...
	'SpecifyObjectiveGradient',false, ...
	'Display','off', ...
	'MaxIterations',40000, ...
	'MaxFunctionEvaluations',2000000, ...
	'PlotFcn',[]);
fprintf('fsolve calculation time:\n');
tic;
[HydraulicState,EquationValue] = fsolve(@(HydraulicState)create_HydraulicCalculationEquation_Numerical(HydraulicState,x,u, ...
	HydraulicOilParameter,HydraulicElementParameter, ...
	HydraulicConnectionParameter),InitialHydraulicState,opt);
toc;

fprintf('fsolve calculation time:\n');
tic;
HydraulicState = solve_HydraulicCalculationEquatition_Numerical(...
	HydraulicParameter);
toc;