function [HydraulicState,HydraulicElementState] = ...
	solve_HydraulicCalculationEquatition_Numerical(...
	HydraulicParameter)
%%
HydraulicCoordinateQuantity = HydraulicParameter.HydraulicCoordinateQuantity;
HydraulicNumericalEquationHandle = HydraulicParameter.HydraulicNumericalEquationHandle;
HydraulicElementParameter = HydraulicParameter.HydraulicElementParameter;
%%
InitialHydraulicState = zeros(HydraulicCoordinateQuantity,1);
opt = optimoptions('fsolve', ...
	'Algorithm','trust-region-dogleg', ...
	'StepTolerance',1e-15, ...
	'FunctionTolerance',1e-15, ...
	'SpecifyObjectiveGradient',false, ...
	'Display','off', ...
	'MaxIterations',40000, ...
	'MaxFunctionEvaluations',2000000, ...
	'PlotFcn',[]);
% fprintf('fsolve calculation time:\n');
% tic;
[HydraulicState,EquationValue] = fsolve(HydraulicNumericalEquationHandle, ...
	InitialHydraulicState,opt);
% toc;
%%
HydraulicElementState = [];
HydraulicElementQuantity = numel(HydraulicElementParameter);
for HydraulicElementNr = 1:HydraulicElementQuantity
	HydraulicElement = HydraulicElementParameter{HydraulicElementNr};
	HydraulicElementType = HydraulicElement.Name;
	HydraulicElementGlobalCoordinate = HydraulicElement.GlobalCoordinate;
	switch HydraulicElementType
		case {'Ideal Constant Pressure Pump','Ideal Constant Pressure Sink'}
			HydraulicElementState{HydraulicElementNr}.p = ...
				HydraulicState(HydraulicElementGlobalCoordinate(1));
			HydraulicElementState{HydraulicElementNr}.Q = ...
				HydraulicState(HydraulicElementGlobalCoordinate(2));
		case {'Electronic Throttle Valve','Back Pressure Valve', ...
				'Double Acting Hydraulic Cylinder'}
			HydraulicElementState{HydraulicElementNr}.p1 = ...
				HydraulicState(HydraulicElementGlobalCoordinate(1));
			HydraulicElementState{HydraulicElementNr}.p2 = ...
				HydraulicState(HydraulicElementGlobalCoordinate(2));
			
			HydraulicElementState{HydraulicElementNr}.Q1 = ...
				HydraulicState(HydraulicElementGlobalCoordinate(3));
			HydraulicElementState{HydraulicElementNr}.Q2 = ...
				HydraulicState(HydraulicElementGlobalCoordinate(4));
	end
end

end