function [Mass,Force] = get_Element_MassForce(...
	qe,dqe,g,BodyParameter)
switch BodyParameter.BodyType
	case 'Rigid Body'
		[Mass,Force] = ...
			RigidBody_MassForce(...
			qe,dqe,g,BodyParameter);
	case 'Timoshenko Beam'
		[Mass,Force] = ...
			TimoshenkoBeam_MassForce(...
			qe,dqe,g,BodyParameter);
	case 'Super Truss Element'
		useEquivalentModel = ...
			BodyParameter.Truss_Parameter.useEquivalentModel;
		if useEquivalentModel
% 			q1 = qe(1:6);
% 			q2 = qe(7:12);
% 			qe = [q1;1;q2;1];
% 			
% 			dq1 = dqe(1:6);
% 			dq2 = dqe(7:12);
% 			dqe = [dq1;0;dq2;0];
			
			[Mass,Force] = ...
				SuperTrussElement_CubicSpline_MassForce(...
				qe,dqe,g,BodyParameter.Truss_Parameter);
		else
			[Mass,Force] = ...
				Super_Truss_Element_MassForce(...
				qe,dqe,g,BodyParameter);
		end
	case 'Strut Tie Model'
		[Mass,Force] = ...
			Strut_Tie_MassForce(...
			qe,dqe,g,BodyParameter);
	case 'Strut Tie Rope Model'
		[Mass,Force] = ...
			Strut_Tie_Rope_MassForce(...
			qe,dqe,g,BodyParameter);
	case 'Cubic Spline Beam'
		[Mass,Force] = CubicSpline_MassForce(...
			qe,dqe,g,BodyParameter);
	case 'Cubic Spline Rope'
		[Mass,Force] = CubicSpline_Rope_MassForce(...
			qe,dqe,g,BodyParameter);
end
end