function [Mass,Force] = get_Element_MassForce_Symbolic(...
	qe,dqe,g,BodyParameter)
switch BodyParameter.BodyType
	case 'Rigid Body'
		[Mass,Force] = ...
			RigidBody_MassForce_Symbolic(...
			qe,dqe,g,BodyParameter);
	case 'Timoshenko Beam'
		[Mass,Force] = ...
			TimoshenkoBeam_MassForce_Symbolic(...
			qe,dqe,g,BodyParameter);
	case 'Super Truss Element'
		[Mass,Force] = ...
			Super_Truss_Element_MassForce_Symbolic(...
			qe,dqe,g,BodyParameter);
	case 'Strut Tie Model'
		[Mass,Force] = ...
			Strut_Tie_MassForce_Symbolic(...
			qe,dqe,g,BodyParameter);
	case 'Strut Tie Rope Model'
		[Mass,Force] = ...
			Strut_Tie_Rope_MassForce(...
			qe,dqe,g,BodyParameter);
	case 'Cubic Spline Beam'
		[Mass,Force] = CubicSpline_MassForce_Symbolic(...
			qe,dqe,g,BodyParameter);
	case 'Cubic Spline Rope'
		[Mass,Force] = CubicSpline_Rope_MassForce_Symbolic(...
			qe,dqe,g,BodyParameter);
end
end