%% FlexibleBeam_PlanePendulum_Test_Configs
mkdir('Result');
configs = cell(4,2);
ExcelFileNameSet = cell(4,2);
ExcelFileDirSet = cell(4,2);
%% Excel File Name
% Cubic Spline Beam
ExcelFileNameSet{1,1} = ...
	'Cubic Spline Beam Pendulum - 1 Segments';
ExcelFileNameSet{2,1} = ...
	'Cubic Spline Beam Pendulum - 3 Segments';
ExcelFileNameSet{3,1} = ...
	'Cubic Spline Beam Pendulum - 5 Segments';
ExcelFileNameSet{4,1} = ...
	'Cubic Spline Beam Pendulum - 10 Segments';
% Timoshenko Beam
ExcelFileNameSet{1,2} = ...
	'Timoshenko Beam Pendulum - 1 Segments';
ExcelFileNameSet{2,2} = ...
	'Timoshenko Beam Pendulum - 3 Segments';
ExcelFileNameSet{3,2} = ...
	'Timoshenko Beam Pendulum - 5 Segments';
ExcelFileNameSet{4,2} = ...
	'Timoshenko Beam Pendulum - 10 Segments';
%% Excel File Directory
% Cubic Spline Beam
ExcelFileDirSet{1,1} = ['Parameter File', ...
	'\Pendulum Test\Cubic Spline Beam Pendulum Test'];
ExcelFileDirSet{2,1} = ['Parameter File', ...
	'\Pendulum Test\Cubic Spline Beam Pendulum Test'];
ExcelFileDirSet{3,1} = ['Parameter File', ...
	'\Pendulum Test\Cubic Spline Beam Pendulum Test'];
ExcelFileDirSet{4,1} = ['Parameter File', ...
	'\Pendulum Test\Cubic Spline Beam Pendulum Test'];
% Timoshenko Beam
ExcelFileDirSet{1,2} = ['Parameter File', ...
	'\Pendulum Test\Timoshenko Beam Pendulum Test'];
ExcelFileDirSet{2,2} = ['Parameter File', ...
	'\Pendulum Test\Timoshenko Beam Pendulum Test'];
ExcelFileDirSet{3,2} = ['Parameter File', ...
	'\Pendulum Test\Timoshenko Beam Pendulum Test'];
ExcelFileDirSet{4,2} = ['Parameter File', ...
	'\Pendulum Test\Timoshenko Beam Pendulum Test'];
%%
parfor TestNr = 1:numel(configs)
	configs{TestNr}.ExcelFileName = ...
		ExcelFileNameSet{TestNr};
	configs{TestNr}.ExcelFileDir = ...
		ExcelFileDirSet{TestNr};
	configs{TestNr}.ActionFunctionHandle = ...
		get_ActionFunction('None');
	SolveParameter_func(configs{TestNr});
end