%% FlexibleBeam_CantileverBeamSelfGravity_Vibration_Test_Configs
mkdir('Result');
configs = cell(4,2);
ExcelFileNameSet = cell(4,2);
ExcelFileDirSet = cell(4,2);
%% Excel File Name
% Cubic Spline Beam
ExcelFileNameSet{1,1} = ...
	'Cubic Spline Beam - 1 Segments';
ExcelFileNameSet{2,1} = ...
	'Cubic Spline Beam - 3 Segments';
ExcelFileNameSet{3,1} = ...
	'Cubic Spline Beam - 5 Segments';
ExcelFileNameSet{4,1} = ...
	'Cubic Spline Beam - 10 Segments';
% Timoshenko Beam
ExcelFileNameSet{1,2} = ...
	'Timoshenko Beam - 1 Segments';
ExcelFileNameSet{2,2} = ...
	'Timoshenko Beam - 3 Segments';
ExcelFileNameSet{3,2} = ...
	'Timoshenko Beam - 5 Segments';
ExcelFileNameSet{4,2} = ...
	'Timoshenko Beam - 10 Segments';
%% Excel File Directory
% Cubic Spline Beam
ExcelFileDirSet{1,1} = ['Parameter File', ...
	'\Cantilever Beam Self Gravity Test\Cubic Spline Beam Test'];
ExcelFileDirSet{2,1} = ['Parameter File', ...
	'\Cantilever Beam Self Gravity Test\Cubic Spline Beam Test'];
ExcelFileDirSet{3,1} = ['Parameter File', ...
	'\Cantilever Beam Self Gravity Test\Cubic Spline Beam Test'];
ExcelFileDirSet{4,1} = ['Parameter File', ...
	'\Cantilever Beam Self Gravity Test\Cubic Spline Beam Test'];
% Timoshenko Beam
ExcelFileDirSet{1,2} = ['Parameter File', ...
	'\Cantilever Beam Self Gravity Test\Timoshenko Beam Test'];
ExcelFileDirSet{2,2} = ['Parameter File', ...
	'\Cantilever Beam Self Gravity Test\Timoshenko Beam Test'];
ExcelFileDirSet{3,2} = ['Parameter File', ...
	'\Cantilever Beam Self Gravity Test\Timoshenko Beam Test'];
ExcelFileDirSet{4,2} = ['Parameter File', ...
	'\Cantilever Beam Self Gravity Test\Timoshenko Beam Test'];
%%
parfor TestNr = 1:numel(configs)
	configs{TestNr}.ExcelFileName = ...
		ExcelFileNameSet{TestNr};
	configs{TestNr}.ExcelFileDir = ...
		ExcelFileDirSet{TestNr};
	configs{TestNr}.ActionFunctionHandle = ...
		get_ActionFunction('None');
	SolveParameter_func(configs{TestNr});
end