mkdir('Result');
%% Static 50t:50t:400t
clc;clear;close all;
configs = cell(8,1);
parfor LoadMassNr = 1:8%400:50:400
	LoadMass = LoadMassNr * 50;
	configs{LoadMassNr}.ExcelFileDir = [...
		'Parameter File', ...
		'\Lattice boom crane model', ...
		'\Truss Equivalent Model', ...
		'\Load in Air'];
	configs{LoadMassNr}.ActionFunctionHandle = ...
		@(t,x,tspan,ModelParameter)get_Action_None(...
		t,x,tspan,ModelParameter);
	configs{LoadMassNr}.ExcelFileName = [...
		num2str(LoadMass),'t'];
	
	SolveParameter_func(configs{LoadMassNr});
end