function dT_Conjugation = get_dT_Conjugation(phi,dphi)

theta = norm(phi);
if theta == 0
	dT_Conjugation = zeros(3);
else
	dT_Conjugation =  ...
        ((-sin(theta)*theta - 2*(cos(theta)-1))/(theta^4)*skew(phi) + ...
		((1-cos(theta))*theta - 3*(1-sin(theta)))/(theta^5)*skew(phi)*skew(phi)) * ...
        dphi*phi' - ...
		(cos(theta)-1)/(theta^2)*skew(dphi) + ...
		(theta-sin(theta)/theta)/(theta^3) * ...
        (phi*dphi'-dphi*phi'-skew(phi)*skew(dphi));
end

end