function dT = get_dT(phi,dphi)

theta = norm(phi);
if theta == 0
	dT = zeros(3);
else
	dT = (phi'*dphi) * (...
		(-sin(theta)*theta - 2*(cos(theta)-1))/(theta^4)*skew(phi) + ...
		((1-cos(theta))*theta - 3*(1-sin(theta)))/(theta^5)*skew(phi)*skew(phi)) + ...
		(cos(theta)-1)/(theta^2)*skew(dphi) + ...
		(theta-sin(theta)/theta)/(theta^3)*skew(dphi)*skew(phi) + ...
		(theta-sin(theta)/theta)/(theta^3)*skew(phi)*skew(dphi);
end

end