%% ========== PostProcessing_CSB_CTT ===========
%% PostProcessing
%% Cubic Spline Beam(CSB)
%% Calculation Tolerance Test(CTT)
%% =============================================
clear;close all;clc;
%%
ResultParentFolderName{1} = ...
	['Result\', ...
	'Single Long Beam Controlled Pendulum Test\', ...
	'Normal Cosine Angle Drive\'];
SegmentFolderNameBase{1} = 'Angle';
FigureName{1} = 'Normal Cosine Angle Drive';
%
ResultParentFolderName{2} = ...
	['Result\', ...
	'Single Long Beam Controlled Pendulum Test\', ...
	'Constant Moment Drive\'];
SegmentFolderNameBase{2} = 'Axis';
FigureName{2} = 'Constant Moment Drive';
%
ResultParentFolderName{3} = ...
	['Result\', ...
	'Single Long Beam Controlled Pendulum Test\', ...
	'3-Stage Angle Drive\'];
SegmentFolderNameBase{3} = 'Angle';
FigureName{3} = '3-Stage Angle Drive';
%%
for FigureNr = 1:3
	PostProcessing_CSB_GIPNT_PlotFunc(...
		ResultParentFolderName{FigureNr}, ...
		SegmentFolderNameBase{FigureNr}, ...
		FigureName{FigureNr});
end
%%
function PostProcessing_CSB_GIPNT_PlotFunc(...
	ResultParentFolderName,SegmentFolderNameBase, ...
	FigureName)
SegmentNr_Set = [1;3;5;10];
Tol_Set = {[0.01;0.01];[0.0001;0.0001]};
ResultData = cell(numel(Tol_Set),numel(SegmentNr_Set));
%%
PlotFormat{1,1} = 'k-';
PlotFormat{1,2} = 'r-';
PlotFormat{1,3} = 'g-';
PlotFormat{1,4} = 'b-';
%
PlotFormat{2,1} = 'k--';
PlotFormat{2,2} = 'r--';
PlotFormat{2,3} = 'g--';
PlotFormat{2,4} = 'b--';
%%
FigureObj = figure('Name',FigureName);
AxisObj{1,1} = subplot(1,2,1);title(AxisObj{1,1},'x_end');
AxisObj{1,2} = subplot(1,2,2);title(AxisObj{1,2},'z_end');
for AxisNr = 1:numel(AxisObj)
	hold(AxisObj{AxisNr},'on');
end
%%
for TolNr = 1:numel(Tol_Set)
	RelTol = Tol_Set{TolNr}(1);
	AbsTol = Tol_Set{TolNr}(2);
	ToleranceFolderName = [...
		'RelTol=',num2str(RelTol),' ', ...
		'AbsTol=',num2str(AbsTol),'\'];
	for SegmentNr = 1:numel(SegmentNr_Set)
		SegmentQuantity = SegmentNr_Set(SegmentNr);
		SegmentFolderName = [...
			'Cubic Spline Beam Pendulum ', ...
			SegmentFolderNameBase,' Drive - ', ...
			num2str(SegmentQuantity), ...
			' Segments\'];
		ResultFolderName = [...
			ResultParentFolderName, ...
			ToleranceFolderName, ...
			SegmentFolderName];
		ResultData{TolNr,SegmentNr} = load(...
			[ResultFolderName,'Result.mat']);
		%%
		x_set = ResultData{TolNr,SegmentNr}.x_set;
		t_set = ResultData{TolNr,SegmentNr}.t_set;
		q_set = x_set(:,1:size(x_set,2)/2);
		%%
		x_end = q_set(:,end-6);
		z_end = q_set(:,end-4);
		%%
		plot(AxisObj{1,1}, ...
			t_set,x_end,PlotFormat{TolNr,SegmentNr});
		plot(AxisObj{1,2}, ...
			t_set,z_end,PlotFormat{TolNr,SegmentNr});
	end
end
for AxisNr = 1:numel(AxisObj)
	legend(AxisObj{AxisNr},...
		'0.01 1-Seg', ...
		'0.01 3-Seg', ...
		'0.01 5-Seg', ...
		'0.01 10-Seg', ...
		'0.0001 1-Seg', ...
		'0.0001 3-Seg', ...
		'0.0001 5-Seg', ...
		'0.0001 10-Seg', ...
		'Location','best');
	hold(AxisObj{AxisNr},'off');
end
end